version: '3.8'

services:
  bot:
    build: .
    container_name: discord-bot
    restart: always
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: ["node", "app.js"]
    networks:
      - bot-network

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - bot-network
    env_file:
      - .env

volumes:
  mongo-data:

networks:
  bot-network:
